import Image from "next/image";
import Link from "next/link";
import { breadcrumbJsonLd, pageMetadata, site } from "@/lib/seo";

export const metadata = pageMetadata({ title: "TantaGlobal Assist | Global talent, hired with intent", description: "A certification-led placement path for US businesses and Filipino virtual assistants.", path: "/", image: "/og-home.svg" });
const breadcrumbs = breadcrumbJsonLd([{ name: "Home", path: "/" }]);

const steps = [
  ["01", "Start with the real work", "Employers tell us what needs to be done. Candidates share where they are today."],
  ["02", "Build readiness", "Candidates complete the Academy step and develop the habits US clients expect."],
  ["03", "Match with intention", "We support a focused shortlist and a professional handoff, not a crowded directory."],
];

export default function HomePage() {
  return <div className="bg-instruments-daylight text-instruments-teak">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }} />
    <div className="border-b border-instruments-shadow/20"><div className="section-container flex items-center justify-between py-3"><span className="instr-filing">TantaGlobal Assist · Rio Rancho + Cebu</span><a href="https://tantaholdings.com" className="instr-filing hover:text-instruments-sea">Tanta Holdings →</a></div></div>
    <section className="section-container grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1fr_.82fr] lg:py-24">
      <div><p className="instr-meta mb-6">TantaGlobal Assist</p><h1 className="instr-display max-w-2xl text-5xl font-medium leading-[.91] tracking-[-.055em] sm:text-7xl">Global talent,<br /><em className="font-serif font-normal text-instruments-sea">hired with intent.</em></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-instruments-shadow">A clearer path between trained virtual assistants and US businesses that need dependable work done well.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/hire" className="instr-btn-primary">Hire a VA <span>→</span></Link><Link href="/apply" className="instr-btn-ghost">Apply as a VA <span>→</span></Link></div><p className="mt-12 border-t border-instruments-shadow/20 pt-5 text-xs text-instruments-shadow">Certification-led candidate pipeline · Employer brief intake · Placement follow-through</p></div>
      <div className="relative mx-auto h-[430px] w-full max-w-[440px] overflow-hidden rounded-t-[170px] bg-instruments-sea/15 sm:h-[520px]"><Image src="/images/hero/remote-team-call.jpg" alt="Remote colleagues working together" fill priority sizes="(min-width:1024px) 38vw,90vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-instruments-teak/45 to-transparent" /><div className="absolute bottom-5 left-5 right-5 bg-instruments-vellum/95 p-5"><p className="font-serif text-lg leading-tight">The right placement starts before the first interview.</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.16em] text-instruments-bronze">Training + placement, connected</p></div></div>
    </section>
    <section className="bg-instruments-ink py-16 text-instruments-vellum"><div className="section-container grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><p className="instr-meta text-instruments-gold">A different standard</p><p className="instr-display max-w-4xl text-3xl leading-[1.08] sm:text-5xl">We do not treat people as profiles to sort. We build <span className="font-serif italic text-instruments-gold">readiness, fit, and trust</span> into the process.</p></div></section>
    <section className="section-container py-20 sm:py-28"><div className="grid gap-8 border-b border-instruments-shadow/20 pb-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="instr-meta mb-4">How it works</p><h2 className="instr-display text-5xl font-medium leading-[.92] tracking-[-.05em] sm:text-6xl">Three steps.<br />One stronger start.</h2></div><p className="text-base leading-relaxed text-instruments-shadow">Clear expectations make a better experience for both sides of the placement conversation.</p></div><div className="grid gap-8 py-10 md:grid-cols-3">{steps.map(([number,title,copy]) => <article key={number} className="border-t border-instruments-shadow/25 pt-5"><span className="font-serif text-xl text-instruments-bronze">{number}</span><h3 className="mt-6 font-serif text-2xl font-normal">{title}</h3><p className="mt-3 text-sm leading-relaxed text-instruments-shadow">{copy}</p></article>)}</div></section>
    <section className="bg-[#e9ddd0]"><div className="section-container grid gap-8 py-16 lg:grid-cols-2"><div><p className="instr-meta mb-4">For employers</p><h2 className="font-serif text-4xl font-normal leading-tight">More signal. Less sorting.</h2><p className="mt-4 max-w-md leading-relaxed text-instruments-shadow">Share the role, hours, and expectations. We route you toward a shortlist built for the work you actually need done.</p><Link href="/hire" className="mt-7 inline-block border-b border-instruments-teak pb-1 text-sm font-semibold">Request a shortlist →</Link></div><div className="border-t border-instruments-shadow/20 pt-8 lg:border-l lg:border-t-0 lg:pl-12 lg:pt-0"><p className="instr-meta mb-4">For candidates</p><h2 className="font-serif text-4xl font-normal leading-tight">A measured route into client work.</h2><p className="mt-4 max-w-md leading-relaxed text-instruments-shadow">Apply, complete the Academy step, and enter the placement queue with a stronger professional profile.</p><Link href="/apply" className="mt-7 inline-block border-b border-instruments-teak pb-1 text-sm font-semibold">Apply for placement →</Link></div></div></section>
    <section className="bg-instruments-teak text-instruments-vellum"><div className="section-container flex flex-col justify-between gap-8 py-20 lg:flex-row lg:items-end"><div><p className="instr-meta mb-5 text-instruments-gold">The next step</p><h2 className="instr-display text-5xl font-medium leading-[.92] sm:text-6xl">Make the work<br /><em className="font-serif font-normal text-instruments-gold">more possible.</em></h2></div><a href={site.academyUrl} className="border-b border-instruments-gold pb-2 text-sm font-semibold">Explore Academy training →</a></div></section>
  </div>;
}
